### ISSUE TITLE
Praefect Database creation requires database named gitlab even though name is parameterized

### ISSUE THREAD

**Issue by hswope-arcweb** [aws-quickstart/quickstart-eks-gitlab#100]
In running the quick start, I am receiving a failure when creating the praefect database. It fails saying database gitlab does not exist. In the parameters I set the database name to something else. I am going to use the default name to see if this clears the error up, but I wanted to mention the issue here.

Error:

        {
            "StackId": "arn:aws:cloudformation:us-east-1:xxxxxxxxxxxx:stack/xxxxx-GitLabStack-TPJCKP31F2D7-Praefect-U4E5RJMCEFYP/433f1c90-2e00-11ec-bc69-0a975ef1459f",
            "EventId": "PraefectDatabase-CREATE_FAILED-2021-10-15T21:43:00.019Z",
            "StackName": "xxxxx-GitLabStack-TPJCKP31F2D7-Praefect-U4E5RJMCEFYP",
            "LogicalResourceId": "PraefectDatabase",
            "PhysicalResourceId": "xxxxx-GitLabStack-TPJCKP31F2D7-Praefect-U4E5RJMCEFYP_PraefectDatabase_EGGKKLQ5",
            "ResourceType": "Custom::CreatePraefectDatabase",
            "Timestamp": "2021-10-15T21:43:00.019000+00:00",
            "ResourceStatus": "CREATE_FAILED",
            "ResourceStatusReason": "Received response status [FAILED] from custom resource. Message returned: FATAL:  database \"gitlab\" does not exist\n (RequestId: 1cdcf568-ed0d-4b99-b811-e49c1bde0e3a)",
            "ResourceProperties": "{\"ServiceToken\":\"arn:aws:lambda:us-east-1:xxxxxxxxxxxx:function:xxxxx-GitLabStack-TPJCKP31F-CreateDatabaseLambda-Ks5FgfK2mTwY\",\"UserName\":\"gitlab\",\"DBName\":\"praefect\",\"Host\":\"xxxxx-gitlabstack-tpjckp31f2d7-auroradbcluster-a1we4tk206qj.cluster-cpb0ozs9ybcl.us-east-1.rds.amazonaws.com\",\"Password\":\"****\"}"
        },

**Comment by kolomied** [comment]
An obsolete issue - Praefect and GitLab databases use separate RDS clusters now. The custom resource mentioned in the description above is not used anymore.
