### ISSUE TITLE
[HL: DONE] Short Term: Critical: Automatic Generation of DbUserPassword

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#24]
Currently DBUserPassword is specified in .taskcat.yaml.  It would be better if it was autocreated and stored in Secrets Manager by default.

**Comment by kolomied** [comment]
- [ ] Generate password and store in Secrets Manager secret
- [ ] Remove password parameter from entry CFN templates
- [ ] Remove password from taskcat file

**Comment by DarwinJS** [comment]
Seems like we'll need DB secret for the Praefect database since it is separating out - but in the first iteration I'm just going to get it all going with a single password.

**Comment by kolomied** [comment]
@DarwinJS This is implemented as part of #111
