### ISSUE TITLE
Medium Term: Complete Clean up

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#29]
- Empty buckets so they will delete
- Remove Gitaly servers from DNS so they will delete (Seems zones that have more than SOA and NS won't automatically delete via CF): https://github.com/aws-quickstart/quickstart-eks-gitlab/issues/36
- instuctions for cloudwatch logs clean up?

**Comment by kolomied** [comment]
@DarwinJS Please verify and close this one - think we've done everything for the clean cleanup
