### ISSUE TITLE
Short Term: Documentation: Reference Chart Ver = GitLab Ver Mapping Page

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#31]
Documentation should clearly articulate that choosing a chart version is how you choose a GitLab version with a link to this page: https://docs.gitlab.com/charts/installation/version_mappings.html

Should also be a comment by the parameter where ever it appears in templates.

**Comment by kolomied** [comment]
@DarwinJS I think we can close this one - done as part of #64

**Comment by DarwinJS** [comment]
Added to docs and CF form.
