### ISSUE TITLE
Short Term: Gitaly DNS Entries Block Teardown

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#36]
![Screen Shot 2021-04-14 at 1 37 41 PM](https://user-images.githubusercontent.com/11597190/114754448-98095a80-9d26-11eb-92d7-9c4e59bd427a.png)

**Comment by kolomied** [comment]
@DarwinJS Fixed in #72 by @gargana, can be closed

**Comment by DarwinJS** [comment]
Completed in latest release.
