### ISSUE TITLE
Redirect 80 to 443 for GitLab Instance

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#43]
Can be done in an advanced load balancer (non-classic) or the GitLab Charts Value (should work for all scenarios?)

This will avoid the common problem of users logging in on port 80 and getting the 422 error from GitLab.  It's hard to figure out the root cause because the login page displays and responds.

Should also consider whether cert-manager and let's encrypt is a good idea for production deployments?
- e.g. let's encrypt requires port 80 inbound to work properly.

**Comment by kolomied** [comment]
@DarwinJS done in #52, can be closed

**Comment by DarwinJS** [comment]
Done in latest release.
