### ISSUE TITLE
Long Term: Test EKS Node AutoScaling from 5K to 10K Ref Arch

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#54]
1. Setup Gitaly for 10K.
2. Setup Cluster hosts and initial pod values for 5K.
3. Set maximum pod values to max for 10K performance test.
4. Run gpt at 10K levels for a couple hours.
5. Observe:
    - whether 10K Reference Arch levels are reached by autoscaling alone.

**Comment by kolomied** [comment]
@DarwinJS can we close this one based on the results of the latest 10k test you did with autoscaler enabled?

**Comment by DarwinJS** [comment]
10K autoscaling tested and documented
