### ISSUE TITLE
Short Term: Eliminate Ec2 Keypair Requirement

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#56]
It's an antiquated requirement because:
* It is currently a prepatory, manual step
* SSM agent is installed on bastions and is accessible via the console, or with the CLI extension from outside the environment
* could still be used if *optionally* provided (I have the logic for this in the Runner ASG automation)

**Comment by kolomied** [comment]
This is already supported in the latest EKS QS

**Comment by tlindsay42** [comment]
Implemented in #162
