### ISSUE TITLE
[HL] Changes in GitLab 14 Incompatibility with Classic LB

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#84]
Apparently this merge request is creating problems for customers attempting to use GitLab 14.x and AWS Classic Load Balancers: https://gitlab.com/gitlab-org/omnibus-gitlab/-/merge_requests/5461#note_629643241

Perhaps we should enable and default to another load balancer type for hard launch.

This change may be related or needed? https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/2090

**Comment by gargana** [comment]
I will work on a constraint to at least call this out before resources are deployed.

**Comment by DarwinJS** [comment]
https://gitlab.com/gitlab-com/alliances/aws/public-tracker/-/issues/16

**Comment by DarwinJS** [comment]
I will research if we have GitLab Issues for the charts to create other ELB types.
